### ISSUE TITLE
Line break being inserted after <bibl>

### ISSUE THREAD

**Issue by aewingate** [IUBLibTech/newton_chymistry#113]
On the current versions of Carbon and Possum, a line break is being erroneously inserted after each <bibl> tag

See manuscript: 
![image](https://user-images.githubusercontent.com/72820848/138948881-12d11df7-24ae-40c0-801b-d186281cf448.png)

See live site:
![image](https://user-images.githubusercontent.com/72820848/138948663-fcfb440f-433a-4ffc-b5f3-8949d289ee49.png)
_It's not visible on the live site, but there are `<bibl>`s around each of the "Sec XX"_

See Carbon:
![image](https://user-images.githubusercontent.com/72820848/138948789-cf434d8a-8da7-4f24-870f-ca6f12794883.png)

See Possum: 
![image](https://user-images.githubusercontent.com/72820848/138948957-0f29ab27-c314-4981-b0b5-8d162039a98a.png)

**Comment by aewingate** [comment]
Yes! I think that works! It's weird though that extra lines are appearing only after the bibl within the `<p>`. I can't check on other manuscripts on Carbon to see if it's doing it elsewhere because my VPN is not working well.

**Comment by tubesoft** [comment]
We found in the meeting that ALCH00063-11 still seems to be rendered improperly. I still have to work on that.

**Comment by mdalmau** [comment]
That means that we will need a new compilation of 63, then.  Is that correct Wally?

 

 

 

From: Takatomo Inoue ***@***.***>
Reply-To: IUBLibTech/newton_chymistry ***@***.***>
Date: Tuesday, November 2, 2021 at 2:35 PM
To: IUBLibTech/newton_chymistry ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] Re: [IUBLibTech/newton_chymistry] Line break being inserted after <bibl> (Issue #113)

 

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.

 

We found in the meeting that ALCH00063-11 still seems to be rendered improperly. I still have to work on that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tubesoft** [comment]
Hello @aewingate 
I quickly looked at the rendered page of ALCH00063-11, comparing it with MS. I actually could not find any rendering issues so far. Would you be able to point out any issues from the screenshot below?

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/17519127/139949348-152e59ca-5c9e-4852-8267-50f089557b5f.png">
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/17519127/139949385-e7222b53-b76c-4262-b381-f91e224706b5.png">

**Comment by aewingate** [comment]
Hey @tubesoft, looking at what you have there, it looks good to me, but I don't know why it would look weird for Jim and not for you if you haven't changed anything yet.

The VPN still isn't working with my laptop so I can't see what it looks like on there, but I got it to work on my iPad. I just looked at this same page on Chrome, Safari, and Firefox on my ipad on Carbon and I'm seeing the same addition of extra lines as Jim was seeing (see pictures).
![image](https://user-images.githubusercontent.com/72820848/139953367-30d9a79d-f720-416e-a6d0-63568fcc8c8a.png)
![image](https://user-images.githubusercontent.com/72820848/139953383-5aa54722-6f94-4eb5-ac0b-84475e8897ac.png)

**Comment by mdalmau** [comment]
If we don’t need to change the encodings to fix this, the compiled version I sent before the weekend should be good enough to let us test Takatomo’s merge version of the code.

During the meeting today, I tried to determine whether we needed to recompile the combined document given this issue.

I think that none of the encoding I downloaded Thursday needs to be changed to fix this.

Instead, the XSLT templates rendering the bibls are producing an unwanted line feed, maybe in a div that needs to be caught and handled.

Wally

**Comment by tubesoft** [comment]
@mdalmau Yes, the issue that @aewingate  showed with the Carbon page should be fixed in the next merge. I actually self-answered this issue in #106. Thus, I think the xslt code won't be changed, while adding `<p>` tag rendering options will be included in my next commit. However, now I am thinking I initially might have misunderstood the issue a bit. @aewingate, do we still need a feature for suppressing margin between paragraphs?

**Comment by aewingate** [comment]
@tubesoft I don't think we need a feature for suppressing the space between paragraphs since the issue seems to be with the bibls.

**Comment by aewingate** [comment]
@tubesoft I think my theory from yesterday about the issue being with the notes is right. I just looked in Keynes MS. 57 (ALCH00046), on Carbon and on the live site, and it is only after bibls with notes inside them that the extra line breaks are inserted.

This is the live site:
![image](https://user-images.githubusercontent.com/72820848/142270267-516c3887-488b-49a6-8f6d-e7bbe5162350.png)
The citations with blue lines under them end up having notes and the ones with red lines under them don't have notes. I'm just using this as the baseline of where the line breaks should actually be!

This is Carbon:
![image](https://user-images.githubusercontent.com/72820848/142270521-0e69095d-719d-4cc8-bc92-e48ef3d448ae.png)
You can see that the blue line citations all have breaks after them while the red line ones don't. If it was the bibls themselves causing the issue, I think there would be a break on Carbon between 531 and "Hanc solutionem" in "531. Hanc solutionem" and between "p. 536" and "Anima hic pro" in "p. 536. Anima hic pro"

I guess the only notes that need line breaks after them are `<note type="annotation">` and `<note type="editorial">` as long as `<note type="editorial">` doesn't also have the attribute `place="in-line"`. `<note type="biblio">` and just plain `<note>` (the ones mentioned in issue #115) don't need line breaks after htem

**Comment by tubesoft** [comment]
Thank you @aewingate,

`<note type="biblio">` in `<bibl>` popups has an independent algorithm from other `<note>` element rendition. The linebreak issue after `<bibl>` is supposed to be fixed in the next update since I already figured it out in #106.
To show the proof, my local environment renders like this:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/17519127/142333052-b428e116-3dab-4161-afa0-aad50075f8e1.png">

On the other hand, since the issue for #115 has a different rendering process, it is not still fixed yet, which I will work on it soon.

**Comment by wehooper** [comment]
Issue is resolved.
