### ISSUE TITLE
Extra break added after marginal notes

### ISSUE THREAD

**Issue by aewingate** [IUBLibTech/newton_chymistry#115]
I'm checking over the rendering on Carbon of ALCH00063-04, and I'm noticing that marginal notes are being rendered with a line break after them, and there shouldn't be.
In the TEI, there's no line break after this note:
![image](https://user-images.githubusercontent.com/72820848/141858274-f4b58d11-a81e-4796-9bee-1dea35b0983a.png)

But in Carbon, there's a break (and this is on fol. 4.2r):
![image](https://user-images.githubusercontent.com/72820848/141858351-ce99a5e8-cf25-40d7-93e2-7f2fbf590962.png)

On the live site, the note is inline with the text:
![image](https://user-images.githubusercontent.com/72820848/141858456-535efd76-df46-432f-9f98-d9efc29a69fe.png)

And here's the manuscript for good measure:
![image](https://user-images.githubusercontent.com/72820848/141858523-d4146749-4e97-4b04-a5ad-27f00a2b6f1d.png)

**Comment by tubesoft** [comment]
I found that the CSS actually creates a line break.

```css
.place-left {
	text-align: left;
	display: block;
}
```
By setting the element `place="left"`, the element becomes a block element, which creates a line break.
If we look at line 345 of `ALCH00063-04.xml` (latter half of 4.1r), I does not have `<note>`element, and there is no line breaks.
```xml
<g ref="#UNx261e">☞</g> Efficiat igitur ut separetur spiritus ab aqua, ut putrescat &amp; appareat granum <lb/>
```

I guess we might have to think about several things besides rendering process.
I just wondered if we really need `<note>` for the finger pointing sign since I don't get the meaning of `<note>` here.
If we want to show that sign is on the margin, I just would think we should keep the line break just as we dealt with the text on the right margin and note that it was on the left margin. (I wanted to show an example, but I could not find quickly.)

So far, there is no process for `<note>` element without `type` attribute in the xslt code. Do we need to create special rendition process for this case?

**Comment by aewingate** [comment]
We should ask tomorrow in the general meeting, but I get the impression based on the live site that the team's preference would be for these types of notes not to have line breaks. Semantically, I think they'd still want them to be encoded as `<note>` since they are extra notes in the margin versus part of the continuous main text (the "authorial notes" in the encoding guide https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=531699051#EncodingGuide-notes). So my tentative answer is that there should be a special rendition process for this case.

**Comment by tubesoft** [comment]
Yeah, we should. One thing that I care about is consistency with right margin authorial notes. Of course, the right margin ones always have independent lines because it is technically impossible to make a specific inline element align right. I personally think we should treat left and right margins in the same way. Let us think of the case that the left margin note on a certain page consists of a long line. Since that line should be tagged in the same way by `<note place="left"></note>`, if it is rendered as an inline element, it will be inserted in a random line, which would not make sense as a text. Therefore, I still think we should leave it as it is.

**Comment by tubesoft** [comment]
In the meeting, we decided that make both right and left margins inline elements, enclose with daggers, and add comments like "<in right mg.>" just as found in the live site.

**Comment by aewingate** [comment]
@tubesoft Just letting you know that I re-encoded the manicule on 1r of 63.04 as `<note place="left">`. Have not re-indexed yet, so it won't show up on Carbon yet.

**Comment by tubesoft** [comment]
So far it goes like this:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/17519127/144342203-99efed61-f3cc-4f35-950c-2813ca9f20de.png">

As for the right column (ALCH00026 - 4r):
Local environment:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/17519127/144341841-3a195ec5-8c55-4edf-b45e-1a1498804de9.png">
Live page:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/17519127/144342075-550f81a2-b837-4e86-abb5-b2fcd88d9709.png">
Manuscript:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/17519127/144341906-564b3c2f-ca43-4d63-a5aa-39af8bba2b38.png">

**Comment by aewingate** [comment]
I think that looks really great! To my eyes it sets off the marginal note enough from the text.

**Comment by wehooper** [comment]
This is working correctly now.
