### ISSUE TITLE
<fw> in seg type=choice <orig/reg> catchword position in parallel columns in Keynes 19

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#51]
Another detail.

At the bottom of the left column of f.1r of Keynes 19, Newton added the morpheme/catch word "ra" noting that the last syllable of "corpora" would appear at the top of 1v, following his usual practice.

The encoding construction is complex: and \<fw\> in the \<orig\> and \<reg\> forks.

In P5, the "ra" seems to sit on the right boundary of the column, while in the P4 it somehow sits to the left of the boundary. I'm not sure if it is a problem.

ALCH00008.xml lines 473-484.
P5: http://carbon.dlib.indiana.edu:8220/text/ALCH00008/diplomatic#?c=&m=&s=&cv=
P4: http://carbon.dlib.indiana.edu:8215/newton-dev/mss/dipl/ALCH00008/

**Comment by Conal-Tuohy** [comment]
I had neglected to specify a gutter between the two columns. I've added a 2em gutter, and made a tweak to the XSLT and CSS to render the `<fw>` as an HTML `<span>` rather than `<div>` (since it appears a "flow" context) but to render it with `display: block` so that the right-aligned text is aligned within the available horizontal space, rather than within the width of a `<span>` which is definitionally the width of the textual content of that `<span>`.

**Comment by Conal-Tuohy** [comment]
I'm a little doubtful that the example is actually a catchword, strictly speaking; shouldn't it also appear at the top of the next column, if that's what it is?

**Comment by mdalmau** [comment]
This requires @wehooper's review!

**Comment by wehooper** [comment]
This issue is completed.

The 'ra' catchword actually appears at the top of the following folio, f.1v, following the flow of the main body in the left column. The right column is more like the area for footnotes at the bottom of the page in a generic monograph.

Thanks for the fix.
