### ISSUE TITLE
Need to update the purls before hard launch of new website

### ISSUE THREAD

**Issue by Conal-Tuohy** [IUBLibTech/newton_chymistry#54]
The metadata summaries of each text include a suggested citation which includes: the URL `http://purl.dlib.indiana.edu/iudl/newton/` followed by the value of the XPath expression `//altIdentifier/idno[@type='iunp']`

**Comment by mdalmau** [comment]
Pending the resolution of issue #55

**Comment by randalldfloyd** [comment]
@mdalmau In the PURL pattern, make sure the static part of the string carries the `iiif` format disambiguation, like: https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00095

That's a format signal that distinguishes between being sent to Pages for the manifest or the default context of the item in the Newton site itself.

**Comment by mdalmau** [comment]
Discussed that @Conal-Tuohy would add this to his converter script once we have the P5 repo working.  Ugh.

**Comment by mdalmau** [comment]
The PURLs are in the header but the viewer isn't loading the images: 
 <idno type="iiif-manifest">https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00001</idno>.  See issue #53

**Comment by randalldfloyd** [comment]
@mdalmau I can trace in the browser to see what I think the viewer is doing (or not.) But thinking out loud logically, the PURL resolves, the manifest is valid, and if you view the work that it resolves to in the Pages context the images load: https://pages.dlib.indiana.edu/concern/scanned_resources/d73666d868

**Comment by mdalmau** [comment]
@randalldfloyd so are you suggesting it's a viewer issue? @Conal-Tuohy, could you also take a look.  I have loaded several manuscripts and clicked on the page image icon and the viewer hangs: https://newton.dlib.indiana.edu/search/.

**Comment by randalldfloyd** [comment]
@mdalmau I'm thinking less of the viewer in general and more along the lines of a transformation problem. It was working before end-to-end with no changes in either Pages or the PURL config, and it was working in context of the Newton viewer without any application changes, so that leaves the only variable that changed - the indexed documents.

**Comment by mdalmau** [comment]
Right. @randalldfloyd you may be on to something because I added the W3c schema pointer to based on what we tested that Xubmit was able to tolerate.  In looking at @Conal-Tuohy's update to the XSLT, which wasn't committed, I see now that he has namespace and other information in the TEI header that I don't have in the newly submitted P5 files in Xubmit.  I feel stuck right now.  I think I need @Conal-Tuohy to verify and confirm.

**Comment by randalldfloyd** [comment]
@mdalmau When you say the XSLT that wasn't committed, you mean it wasn't committed to the Github repo, or that it was and I missed that I needed to update the deployed Newton web from current master to pick it up?

**Comment by Conal-Tuohy** [comment]
I've just taken a look at this myself. I checked a random document on the production site and I could see the images are not loading.

https://newton.dlib.indiana.edu/text/ALCH00086/normalized

I viewed the P5 source for that file, using the admin page:

https://newton.dlib.indiana.edu/p5/ALCH00086.xml

I looked for the IIIF manifest in the header:

```xml
<idno type="iiif-manifest">https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00086</idno>
```

I accessed the URL https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00086

I was redirected to http://server1.variations2.indiana.edu/cgi-bin/access?ALCH00086/manifest

The result was a 404

**Comment by Conal-Tuohy** [comment]
Reading back up this thread, I noticed @mdalmau that you'd posted a reference to a document whose IIIF manifest URL _did_ resolve (https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00001) and referring to issue #53.

I opened the corresponding web page and viewed the JavaScript console in my browser. The UniversalViewer JavaScript code is logging the following error:

> Blocked loading mixed active content “http://webapp1.dlib.indiana.edu/purl/purlResolver?id=/newton/iiif/ALCH00001”

I opened the "Network" tab in Firefox's Developer Tools menu, and accessed the IIIF manifest URL for this text:
https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00001
The response from the PURL resolver was a 302 (Moved temporarily), including a Location header which specified the new URL http://webapp1.dlib.indiana.edu/purl/purlResolver?id=/newton/iiif/ALCH00001
I think this is the problem right here: this new URL Is an HTTP (rather than HTTPS) URL. These days browsers do not permit pages which were loaded securely (i.e. over HTTPS) to access insecure resources (loaded over HTTP). This is what browser folks call "mixed content" (not to be confused with the term "mixed content" in text markup!). Note that if you do actually attempt to access that HTTP URL directly, in a browser, it does in fact redirect to an HTTPS URL, but unfortunately, within the context of a secure page, the browser is not going to speculatively make an insecure request, so the effect of redirecting from the HTTPS PURL to an HTTP URL is to block the request.

In short, I think the fix is to reconfigure the PURL server to ensure it redirects to an HTTPS URL.

In addition, the JavaScript console shows another error:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00001. (Reason: CORS request did not succeed).

The earlier ("mixed content") error means it's not easy to test this, but I believe this may also be a blocker, and that the PURL server needs CORS configuration as well. I think this error means that even if the response to the PURL request had contained an HTTPS URL, that browser would still not have followed the redirect since the response didn't include an appropriate CORS authorization header either. 

I think any server that's designed to be invoked by JavaScript in a browser should be configured to allow CORS, e.g. by returning an `Access-Control-Allow-Origin` header with an appropriate value (generally `*`, meaning "any host may request this resource").

**Comment by randalldfloyd** [comment]
@mdalmau @Conal-Tuohy So the mixed content was easy to solve; there was an incorrect intermediate redirect to the non-ssl version of our PURL middleware.  The CORS thing puzzles me though because I thought we crossed that bridge way back.  I remember having to have our sysadmin make adjustments at the web server, otherwise it would have never worked all this time.  Is this because we didn't have PURLs at all in the header but instead direct references to the Pages web applications until now?  I thought we had been using PURLs all this time so I was kind of surprised when it didn't work because I thought we had worked all these pain points out already.

**Comment by randalldfloyd** [comment]
@mdalmau @Conal-Tuohy So I traced this thing through and have discovered that not all of our web servers were setup to allow CORS, which is what I thought I had been told was going to happen.  The intermediate hop of `webapp1.dlib` is missing it.  Still leaves me wondering how this was working before unless we had still only been testing with 'webapp-devel.dlib` encoded for the manifests.

**Comment by randalldfloyd** [comment]
@mdalmau @Conal-Tuohy  Okay finally, I think this all works again.  The first issue was my bad - I had, as Con suggested, incorrectly configured one of my PURL hops to point to an internal resolver as `http` and created a mixed content problem.  Easy fix, but then the fun started.  We had worked out all of this CORS stuff before, but there was a tricky twist.  Brian wanted to limit the scope of applying the ACAO header so he was checking the `Origin` header to see if it was an application on one of our servers (a reasonable security measure.)   But, we introduced the redirects by encoding PURLs instead of real server locations and that introduced a surprise.  According to the CORS spec:

> If a cross-origin resource redirects to another resource at a new origin, the browser will set the value of the `Origin` header to null after redirecting.

So, by the time the browser got to the Pages endpoints, the `Origin` header was gone and hence no ACAO header being set in the response.  Brian fixed this by matching rules based on `Referer` instead, which seems to have fixed it.  

So on my machine (Chrome and Firefox), the documents I tested seem to be working again.  If they do not for you, be aware that Chrome seemed to want to cache the response headers of the Pages manifest endpoint (i.e. previous broken responses with no ACAO header) and so you may encounter that.  But this can be isolated from browsers and shown to be working via `curl`. Notice the `Origin` and `Referer` headers being set and the existence of `Access-Control-Allow-Origin` in the response for each PURL resolution hop below:
```
$ curl -i -L -H "Origin: https://newton.dlib.indiana.edu" -H "Referer: https://newton.dlib.indiana.edu/text" https://purl.dlib.indiana.edu/iudl/newton/iiif/ALCH00001
HTTP/1.1 302 Moved Temporarily
Date: Wed, 20 May 2020 21:29:30 GMT
Server: Apache
Location: https://webapp1.dlib.indiana.edu/purl/purlResolver?id=/newton/iiif/ALCH00001
Content-Length: 0
Access-Control-Allow-Origin: https://newton.dlib.indiana.edu
Connection: close
Content-Type: text/plain

HTTP/1.1 302 Moved Temporarily
Date: Wed, 20 May 2020 21:29:31 GMT
Server: Apache
Location: https://pages.dlib.indiana.edu/purl/ALCH00001.iiif
Content-Length: 0
Access-Control-Allow-Origin: *
Connection: close
Content-Type: text/plain

HTTP/1.1 302 Found
Date: Wed, 20 May 2020 21:29:32 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Vary: Accept
Location: https://pages.dlib.indiana.edu/concern/scanned_resources/d73666d868/manifest
Content-Type: text/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: a26a1928-c000-43d0-826d-d5c9abde3c80
X-Runtime: 0.006875
Strict-Transport-Security: max-age=31536000
Access-Control-Allow-Origin: *
Connection: close
Transfer-Encoding: chunked

HTTP/1.1 200 OK
Date: Wed, 20 May 2020 21:29:32 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Vary: Accept
Content-Type: application/json; charset=utf-8
ETag: W/"409f40d96d0fb589cc5853837b57b720"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 492acfbe-11b2-4525-aaeb-becd4aca5df1
X-Runtime: 0.015683
Strict-Transport-Security: max-age=31536000
Access-Control-Allow-Origin: *
Connection: close
Transfer-Encoding: chunked
```

**Comment by Conal-Tuohy** [comment]
This is getting slightly off-topic, but has the Library fully considered the policy of having CORS set up to specifically preclude the use of Indiana's IIIF images and metadata on non-Indiana sites? Is this actually a desired outcome? I do wonder, since the ability to publish images and image metadata in an interoperable way is actually one of the big selling points of IIIF (it's what one of the I's stands for! ;-)

**Comment by mdalmau** [comment]
Our AD is supportive of setting up CORS for interchange.  We are having that discussion internally.  Thanks for bringing it up, @Conal-Tuohy!
