### ISSUE TITLE
sorting Babson MS 1006 after 417-936 in Search/Browse window

### ISSUE THREAD

**Issue by wehooper** [IUBLibTech/newton_chymistry#68]
In the current setup of the document browser, the P5 engine correctly sorts 'Babson MS 1006' before 'Babson MS 417' because '1' precedes '4'.

The easiest machine-ready solution would be to modify all the Babson /idno elements with two spaces before the number, like 'Babson MS  417'. It will look odd in a mixed listing using idno's elsewhere.

Can we use the entity for non-breaking space, &#xA0;, in the TEI header?

**Comment by Conal-Tuohy** [comment]
maybe we can extract the numeric portion of the identifier and sort it numerically? what does this look like in the TEI XML?

**Comment by Conal-Tuohy** [comment]
Actually I think using an additional (regular) space between "MS" and "417" should work. When the string `MS  417` is _displayed_ in HTML, the sequence of two spaces will collapse into a single space anyway, but the extra space _should_ serve to ensure that Solr sorts the string `MS  417` before `MS 1006`, since the `sort` field which Solr uses is being treated as unparsed text, and not parsed into tokens which would discard any extra spaces.

**Comment by mdalmau** [comment]
Closing issues so that we can better track production deployment.  Issues with the tag "future" need to be addressed at some point.
