### ISSUE TITLE
Password Protect or Relocate Admin Dashboard

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#71]
To get to some basic admin features for the new Newton web site, one visits: https://newton.dlib.indiana.edu/admin.  We need to either restrict access to this  page or move some of these functions  elsewhere.

**Comment by Conal-Tuohy** [comment]
I wrote an email to the chymistry list on Dec 10 with the subject "Re: Help! Me verify that mss currently unpublished or showing up in the new site". Among other things I suggested changing the various administrative functions so that the URLs _all_ start with `/admin`, to make it simpler to restrict access to the full set using a front-end proxy. Still happy to do that.

**Comment by randalldfloyd** [comment]
For now, using Tomcat basic authentication configured for individual admin endpoints; deferring relocation of all admin functions under `/admin` until some additional problem or story calls for it.
