### ISSUE TITLE
Paragraph on XProc Code Base for the Tech Implementation Page

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#73]
@Conal-Tuohy, could I get a paragraph from you that replaces the 4th and 5th paragraphs in the technology section?  Including attribution to you as the creator.  

https://newton.dlib.indiana.edu/page/tech

**Comment by Conal-Tuohy** [comment]
I have edited the tech.html page a bit, mostly the paragraphs you mentioned, but also a few other details. 

I had to take three stabs at it, and I mistakenly committed the first set of edits as part of another commit which was supposed to contain just the deletion of a couple of temporary files, but if you want to review the actual changes you can see the commits here:
https://github.com/IUBLibTech/newton_chymistry/commits/master/html/tech.html

I deleted the bits about the server hardware because I guessed they were very likely to be outdated, but I didn't know the actual state of play so didn't replace the deleted text.

Over to you!

**Comment by Conal-Tuohy** [comment]
I have deployed the update to carbon, too, BTW

**Comment by Conal-Tuohy** [comment]
Should my name also appear on the project team page?
