### ISSUE TITLE
Rendering Issues in Normalized & Diplomatic Transcriptions

### ISSUE THREAD

**Issue by mdalmau** [IUBLibTech/newton_chymistry#94]
Things that should be removed in the normalized transcription are not being removed (such as accidental duplications), and in the diplomatic text they aren’t being highlighted the way they are on the current site. Below are two screenshots of ALCH0063.01, 1v. Reported by Alex Wingate. 

https://webapp1.dlib.indiana.edu/newton/mss/norm/ALCH00063 compared to http://possum.dlib.indiana.edu:8197/text/ALCH00063-01/

(toggle to diplomatic) 

Compare screen shots below.

**Comment by mdalmau** [comment]
Possum Screen shot of normalized:
![image004](https://user-images.githubusercontent.com/573273/95989866-cf8b5e80-0df8-11eb-91f3-1e6afd04e3f6.jpg)

Current site screen shot of normalized:
![image004](https://user-images.githubusercontent.com/573273/95989942-e92ca600-0df8-11eb-88f3-4bad1517aff9.jpg)

***And note that if you mouse over or click on the <sic> on the left, nothing happens. Other teal text works fine for mousing over though.

**Comment by mdalmau** [comment]
Possum Screen shot of diplomatic:
![image006](https://user-images.githubusercontent.com/573273/95990053-095c6500-0df9-11eb-92fc-8b3b79fa4d01.jpg)

Current site screen shot of diplomatic:
![image006](https://user-images.githubusercontent.com/573273/95990089-124d3680-0df9-11eb-951b-f8758b25630e.jpg)

**Comment by Conal-Tuohy** [comment]
For some reason I've only just spotted this report. It seems to be still current, though?

I had a quick look at the issue, and it looks like the XSLT really only handles `<sic>` when embedded in a `<choice>`. I think this isn't normally a problem because usually if you're going to tag an error with `<sic>` you are typically also going to provide a correction for it.

https://github.com/IUBLibTech/newton_chymistry/blob/79e16047f5d662a5aafe3c95e0768e5b181e8255/xslt/p5-to-html.xsl#L320

It might be good to edit the XSLT template so that it matches `<sic>` elements even when not inside a `<choice>`.

However, regarding this particular `<sic>`, which tags a duplicated word, the more suitable TEI element is `<surplus>`, which the current XSLT _does_ handle.

**Comment by tubesoft** [comment]
I removed `choice` from  `choice/sic` on line 320 of `p5-to-html.xsl`. It seems to work in my local environment.

**Comment by wehooper** [comment]
The case of accidental duplications (Newton repeats a particle word for example) in the diplomatic version not being removed from the normalized has been fixed. Closing this.
