### ISSUE TITLE
Biblio Popup alignment

### ISSUE THREAD

**Issue by tubesoft** [IUBLibTech/newton_chymistry#97]
If the text tagged by <bibl> is aligned center, the bibl popup also is aligned center. Otherwise, the popup is aligned left. We still might have to talk if we should fix or not, but the consistency would be needed. I think I can deal with it by editing the CSS file.

**Comment by tubesoft** [comment]
I can fix by adding `text-align: left` to `details.tei-bibl div.citation-popup` on tei.css.

**Comment by mdalmau** [comment]
Hi.  Did @wehooper sign off on this?  I don't see a pull request.  I am meeting with Randall tomorrow to at least get the code updated to reflect fixes made by Conal Tuohy and you.  Thanks!

**Comment by tubesoft** [comment]
It is included in the latest commit of the [rendition_issues branch](https://github.com/IUBLibTech/newton_chymistry/tree/rendition_issues) as well as several other issues.

**Comment by wehooper** [comment]
I have been using Oxygen to search for a case where a note type='bibl' tags text that is center-aligned. In the opening lines of Keynes 63 (ALCH00052), a note type='bibl' element immediately follows a centering element but is not contained in it. That case is left aligned as required.

No other cases turn up in xpath searched I can think of.

If someone has an example, please give me a location to check. Otherwise, let's close this issue.

**Comment by tubesoft** [comment]
In `tei.css`, at line 1278-9, the code is like this:
```
details.tei-bibl div.citation-popup {
	text-align: left;
```
This should govern the alignment in pop-up.

If anyone finds that this CSS does not seem to be applied, I will try to fix at the next commit.

**Comment by tubesoft** [comment]
Not just alignment, I set specific font size, color, and so forth at #104

**Comment by wehooper** [comment]
This problem has been fixed, all left justified.
